
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PaqueteVencidoException", targetNamespace = "http://servidor/")
public class PaqueteVencidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PaqueteVencidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PaqueteVencidoException_Exception(String message, PaqueteVencidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PaqueteVencidoException_Exception(String message, PaqueteVencidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.PaqueteVencidoException
     */
    public PaqueteVencidoException getFaultInfo() {
        return faultInfo;
    }

}
