
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EmailRepetidoException", targetNamespace = "http://servidor/")
public class EmailRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmailRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EmailRepetidoException_Exception(String message, EmailRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EmailRepetidoException_Exception(String message, EmailRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.EmailRepetidoException
     */
    public EmailRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
