
package servidor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import servlets.ConfigListener;

/**
 * This class was generated by the XML-WS Tools. XML-WS Tools 4.0.0 Generated
 * source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorImagenesService", targetNamespace = "http://servidor/")
public class PublicadorImagenesService extends Service {

	private final static URL PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
	private final static WebServiceException PUBLICADORIMAGENESSERVICE_EXCEPTION;
	private final static QName PUBLICADORIMAGENESSERVICE_QNAME = new QName("http://servidor/",
			"PublicadorImagenesService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(ConfigListener.cfg.getProperty("imagenesControllerURL"));
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		PUBLICADORIMAGENESSERVICE_WSDL_LOCATION = url;
		PUBLICADORIMAGENESSERVICE_EXCEPTION = e;
	}

	public PublicadorImagenesService() {
		super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME);
	}

	public PublicadorImagenesService(WebServiceFeature... features) {
		super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME, features);
	}

	public PublicadorImagenesService(URL wsdlLocation) {
		super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME);
	}

	public PublicadorImagenesService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME, features);
	}

	public PublicadorImagenesService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PublicadorImagenesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns PublicadorImagenes
	 */
	@WebEndpoint(name = "PublicadorImagenesPort")
	public PublicadorImagenes getPublicadorImagenesPort() {
		return super.getPort(new QName("http://servidor/", "PublicadorImagenesPort"), PublicadorImagenes.class);
	}

	/**
	 * 
	 * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to
	 *                 configure on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns PublicadorImagenes
	 */
	@WebEndpoint(name = "PublicadorImagenesPort")
	public PublicadorImagenes getPublicadorImagenesPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://servidor/", "PublicadorImagenesPort"), PublicadorImagenes.class,
				features);
	}

	private static URL __getWsdlLocation() {
		if (PUBLICADORIMAGENESSERVICE_EXCEPTION != null) {
			throw PUBLICADORIMAGENESSERVICE_EXCEPTION;
		}
		return PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
	}

}
